apiVersion: apps/v1
kind: Deployment
metadata:
  name: cirq-automerge-deployment
spec:
  selector:
    matchLabels:
      app: cirq-automerge
  template:
    metadata:
      labels:
        app: cirq-automerge
    spec:
      containers:
      - name: cirq-automerge
        image: us-docker.pkg.dev/cirq-infra/cirq/automerge